In [1]:
import numpy as np
X = np.array(([2,9],[1,5],[3,6]),dtype=float)
y = np.array(([92],[86],[89]),dtype=float)
print(X)
print("_____________________")
print(y)
print("_____________________")
X = X/np.amax(X, axis=0)
print(X)
print("_____________________")
y = y/100
print(y)

[[2. 9.]
 [1. 5.]
 [3. 6.]]
_____________________
[[92.]
 [86.]
 [89.]]
_____________________
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
_____________________
[[0.92]
 [0.86]
 [0.89]]


In [4]:
class Neural_Network():
    def __init__(self):
        self.inputSize = 2
        self.outputSize = 1
        self.hiddenSize = 3
        self.w1 = np.random.randn(self.inputSize,self.hiddenSize)
        print("w1",self.w1)
        self.w2 = np.random.randn(self.hiddenSize,self.outputSize)
        print("w2",self.w2)
    def forward(self,X):
        self.z = np.dot(X,self.w1)
        self.z2 = self.sigmoid(self.z)
        self.z3 = np.dot(self.z2,self.w2)
        o = self.sigmoid(self.z3)
        print(self.z,self.z2,self.z3)
        return 0
    def sigmoid(self,s):
        return 1/(1+np.exp(-s))
    def sigmoidPrime(self,s):
        return s*(1-s)
    def backward(self,X,y,o):
        self.o_error = y-o
        self.o_delta = self.o_error*self.sigmoidPrime(o)
        self.z2_error = self.o_delta.dot(self.w2.T)
        self.z2_delta = self.z2_error*self.sigmoidPrime(self.z2)
        self.w1 += X.T.dot(self.z2_delta)
        self.w2 += self.z2.T.dot(self.o_delta)
    def train(self,X,y):
        o = self.forward(X)
        self.backward(X,y,o)
NN = Neural_Network()
for i in range(0):
    print("Input:\n"+str(X))
    print("Actual output:\n"+str(y))
    print("Predicted output:\n"+str(NN.forward(X)))
    print("Loss:\n"+str(np.mean(np.square(y-NN.forward(X)))))
    print("\n")
    NN.train(X,y)

w1 [[ 2.4102141   0.64016022 -0.46680556]
 [-0.22613132  0.70785795 -0.51632005]]
w2 [[-0.53473548]
 [-0.55255643]
 [ 2.07512343]]
